{pkgs}: {
  deps = [
    pkgs.jdk
    pkgs.psmisc
    pkgs.xorg.libXScrnSaver
    pkgs.xorg.libXtst
    pkgs.xorg.libXrender
    pkgs.xorg.libXi
    pkgs.xorg.libXcursor
    pkgs.xorg.libxcb
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.freetype
    pkgs.fontconfig
    pkgs.gtk3
    pkgs.gdk-pixbuf
    pkgs.cairo
    pkgs.pango
    pkgs.alsa-lib
    pkgs.mesa
    pkgs.libxkbcommon
    pkgs.libdrm
    pkgs.expat
    pkgs.dbus
    pkgs.cups
    pkgs.at-spi2-core
    pkgs.at-spi2-atk
    pkgs.atk
    pkgs.nspr
    pkgs.nss
    pkgs.glib
    # Playwright WebKit 26.5 is built against the Ubuntu 24.04 WebKit
    # runtime. Keep its native ABI available in the reproducible Nix shell.
    pkgs.gst_all_1.gstreamer
    pkgs.gst_all_1.gst-plugins-base
    pkgs.gst_all_1.gst-plugins-good
    pkgs.gst_all_1.gst-plugins-bad
    pkgs.gst_all_1.gst-plugins-ugly
    pkgs.gst_all_1.gst-libav
    pkgs.gtk4
    pkgs.harfbuzz
    pkgs.vulkan-loader
    pkgs.graphene
    pkgs.icu74
    pkgs.systemd
    pkgs.libxml2
    pkgs.sqlite
    pkgs.libxslt
    pkgs.lcms2
    pkgs.libevent
    pkgs.libopus
    pkgs.libgcrypt
    pkgs.libgpg-error
    pkgs.flite
    pkgs.libwebp
    pkgs.libavif
    pkgs.libepoxy
    pkgs.wayland
    pkgs.libmanette
    pkgs.enchant
    pkgs.hyphen
    pkgs.libsecret
    pkgs.libpsl
    pkgs.nghttp2
    pkgs.woff2
    pkgs.libglvnd
    pkgs.x264
    pkgs.libtasn1
    pkgs.stdenv.cc.cc
    pkgs.libjpeg8
    pkgs.harfbuzzFull
    pkgs.libpng
    pkgs.zlib
    pkgs.x264.lib
  ];
}
