/**
 * Firebase Cloud Functions per Wedding Gallery
 * Gestisce invio email tramite Gmail API con Replit Integration
 */

import * as functions from 'firebase-functions';
import { firestore as firestoreV1 } from 'firebase-functions/v1';
import * as admin from 'firebase-admin';
import { EmailQueue } from './email-queue'; // Assicurati che questo percorso sia corretto

// Initialize Firebase Admin if not already done
if (!admin.apps?.length) {
  admin.initializeApp();
}

// Re-export della funzione isolata (no heavy dependencies)
export { getGalleryMetadata } from './metadata';

type SeoSelectedPhoto = { photoId: string; url: string; section: string; alt: string };
const SEO_SECTIONS = ['Preparativi', 'Cerimonia', 'Coppia', 'Location e ricevimento', 'Festa'];
const seoSlug = (value: string) => value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const photoTime = (value: any) => {
  if (typeof value?.toMillis === 'function') return value.toMillis();
  if (typeof value?.seconds === 'number') return value.seconds * 1000;
  return new Date(value || 0).valueOf() || 0;
};

/**
 * Crea una bozza SEO privata per i matrimoni con foto già caricate.
 * Non pubblica mai la pagina: seoPublished resta false, quindi la revisione e il consenso restano umani.
 */
export const createWeddingSeoDraft = firestoreV1
  .document('galleries/{galleryId}')
  .onWrite(async (change, context) => {
    if (!change.after.exists) return null;
    const gallery = change.after.data() || {};
    if (gallery.seoAutoGeneratedAt || gallery.seoPublished) return null;

    const job = gallery.jobId ? (await admin.firestore().collection('jobs').doc(gallery.jobId).get()).data() : undefined;
    if ((gallery.jobType || job?.jobType) !== 'matrimonio') return null;

    const photosSnapshot = await admin.firestore().collection('photos').where('galleryId', '==', context.params.galleryId).get();
    const rawPhotos = photosSnapshot.docs.map(document => ({ id: document.id, ...document.data() } as any))
      .filter(photo => photo.url && photo.uploadedBy !== 'guest');
    if (!rawPhotos.length) return null;

    const unique = new Map<string, any>();
    rawPhotos.forEach(photo => { if (!unique.has(photo.url)) unique.set(photo.url, photo); });
    const photos = [...unique.values()].sort((a, b) => photoTime(a.createdAt) - photoTime(b.createdAt));
    const clientiIds: string[] = job?.clientiIds || gallery.clientiIds || [];
    const clienti = await Promise.all(clientiIds.slice(0, 2).map((id: string) => admin.firestore().collection('clienti').doc(id).get()));
    const names = clienti.filter(client => client.exists).map(client => String(client.data()?.nome || '').trim().split(/\s+/)[0]).filter(Boolean).join(' e ') || String(gallery.name || '').replace(/^matrimonio\s*/i, '');
    const coverUrl = gallery.coverImageDesktop || gallery.coverImageUrl || gallery.coverImageMobile;
    const cover = photos.find(photo => photo.url === coverUrl);
    const picked: any[] = cover ? [cover] : [];
    const chapters = new Map<string, any[]>();
    photos.forEach(photo => { const key = photo.chapterId || 'senza-capitolo'; chapters.set(key, [...(chapters.get(key) || []), photo]); });
    for (const chapter of chapters.values()) {
      const candidate = chapter[Math.floor(chapter.length / 2)];
      if (candidate && !picked.some(photo => photo.id === candidate.id)) picked.push(candidate);
    }
    const target = Math.min(15, photos.length);
    for (let index = 0; picked.length < target && index < target * 3; index++) {
      const candidate = photos[Math.min(photos.length - 1, Math.floor(((index + 1) * photos.length) / (target + 1)))];
      if (candidate && !picked.some(photo => photo.id === candidate.id)) picked.push(candidate);
    }
    const seoImages: SeoSelectedPhoto[] = picked.slice(0, target).map((photo, index) => {
      const section = SEO_SECTIONS[Math.min(SEO_SECTIONS.length - 1, Math.floor(index * SEO_SECTIONS.length / target))];
      return { photoId: photo.id, url: photo.url, section, alt: `Matrimonio di ${names || 'una coppia'} – ${section.toLowerCase()}` };
    });
    const location = gallery.location || job?.eventLocation || '';
    const church = job?.rituLocation || job?.locationCerimonia || null;
    await change.after.ref.update({
      seoImages,
      seoCoupleNames: names,
      seoLocation: location,
      seoChurch: church,
      seoMunicipality: clienti.find(client => client.exists)?.data()?.citta || null,
      seoStyle: 'fotografia spontanea, reportage ed editoriale',
      seoStory: `Un matrimonio reale raccontato con attenzione ai gesti, alle persone e ai dettagli che hanno reso unica la giornata di ${names}. Image Studio Fotografico di Gennaro Mazzacane è uno studio di fotografia matrimoniale ad Aversa, attivo principalmente tra Caserta, Napoli e Campania, specializzato in fotografia spontanea, reportage ed editoriale.`,
      seoSlug: seoSlug(`matrimonio-${names}-${location}`),
      seoStatus: 'draft',
      seoPublished: false,
      seoAutoGeneratedAt: admin.firestore.FieldValue.serverTimestamp(),
      seoGeneratedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
    functions.logger.info(`Bozza SEO matrimonio creata automaticamente: ${context.params.galleryId}`);
    return null;
  });

/**
 * HTTP Function DISABILITATA - Problemi IAM 403 irrisolvibili da Replit
 * Usare sendNewPhotosNotificationCall (callable) invece
 */
// export const sendNewPhotosNotification = functions.https.onRequest(...);

/**
 * Function per invio notifiche nuove foto - CALLABLE (legacy, non più usata dal frontend web)
 */
export const sendNewPhotosNotificationCall = functions
  .runWith({ secrets: ['REPL_IDENTITY'] })
  .https.onCall(async (data, context) => {
  try {
    functions.logger.info('📧 sendNewPhotosNotificationCall invoked with data:', JSON.stringify(data));

    const { galleryName, newPhotosCount, uploaderName, galleryUrl, recipients } = data;

    // Validazioni dettagliate
    if (!galleryName) {
      throw new functions.https.HttpsError('invalid-argument', 'galleryName is required');
    }
    if (!galleryUrl) {
      throw new functions.https.HttpsError('invalid-argument', 'galleryUrl is required');
    }
    if (!recipients || !Array.isArray(recipients)) {
      throw new functions.https.HttpsError('invalid-argument', 'recipients must be an array');
    }
    if (recipients.length === 0) {
      functions.logger.warn('⚠️ No recipients provided, skipping email');
      return { success: true, message: 'No recipients to notify', notified: 0 };
    }

    functions.logger.info(`📨 Preparing to send notification to ${recipients.length} recipient(s)`);

    const { createNewPhotosEmailHTML } = await import('./gmail');
    const htmlContent = createNewPhotosEmailHTML(galleryName, uploaderName || 'Un ospite', newPhotosCount || 1, galleryUrl);
    const subject = `${newPhotosCount || 1} nuova${(newPhotosCount || 1) > 1 ? 'e' : ''} foto in "${galleryName}"`;

    functions.logger.info(`📧 Sending email with subject: "${subject}"`);
    // Aggiungi l'email alla coda invece di inviarla direttamente
    await EmailQueue.addEmailToQueue(recipients, subject, htmlContent);

    functions.logger.info(`✅ New photos notification added to queue for ${recipients.length} recipient(s)`);

    return {
      success: true,
      message: 'Notification added to queue',
      queued: recipients.length
    };
  } catch (error: any) {
    functions.logger.error('❌ Error adding new photos notification to queue:', {
      error: error?.message || error,
      stack: error?.stack,
      code: error?.code
    });

    // Ritorna errore più dettagliato
    const errorMessage = error?.message || 'Failed to add notification email to queue';
    throw new functions.https.HttpsError('internal', errorMessage, {
      originalError: error?.message,
      code: error?.code
    });
  }
});

/**
 * ✅ VERSIONE PUBBLICA HTTP (CORS-enabled)
 * Endpoint HTTP pubblico per notifiche email nuove foto
 * Supporta CORS da qualsiasi origine (anche Replit)
 * DEPLOYED: questo endpoint è attivo e accessibile via HTTPS
 */
export const sendNewPhotosNotificationPublic = functions
  .runWith({ secrets: ['REPL_IDENTITY'] })
  .https.onRequest(async (req, res) => {
    // CORS - Identico a sendGalleryPasswordV2
    const allowedOrigins = [
      'http://localhost:5173',
      'http://localhost:3000',
      'https://gennaromazzacane.it',
      'https://www.gennaromazzacane.it'
    ];

    const origin = req.headers.origin || '';
    const isAllowedOrigin = allowedOrigins.some(allowed => allowed === origin) ||
                           origin.includes('.replit.dev') ||
                           origin.includes('replit.app');

    if (isAllowedOrigin) {
      res.set('Access-Control-Allow-Origin', origin);
    }
    res.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.set('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    res.set('Access-Control-Max-Age', '3600');

    // Handle preflight
    if (req.method === 'OPTIONS') {
      res.status(204).send('');
      return;
    }

    if (req.method !== 'POST') {
      res.status(405).json({
        error: { code: 'method-not-allowed', message: 'Only POST allowed' }
      });
      return;
    }

    try {
      // AUTENTICAZIONE Firebase
      const authHeader = req.headers.authorization || '';
      if (!authHeader || !authHeader.startsWith('Bearer ')) {
        res.status(401).json({
          error: { code: 'unauthenticated', message: 'Missing Authorization Bearer token' }
        });
        return;
      }

      const idToken = authHeader.replace('Bearer ', '').trim();
      let uid = '';
      try {
        const decoded = await admin.auth().verifyIdToken(idToken);
        uid = decoded.uid;
        functions.logger.info(`🔐 sendNewPhotosNotificationPublic called by uid=${uid}`);
      } catch (authError) {
        functions.logger.error('Auth verification failed:', authError);
        res.status(401).json({
          error: { code: 'unauthenticated', message: 'Invalid token' }
        });
        return;
      }

      // LETTURA DATI DAL BODY
      const data = req.body.data || req.body;
      const {
        galleryName,
        newPhotosCount,
        uploaderName,
        galleryUrl,
        recipients
      } = data || {};

      // VALIDAZIONI
      if (!galleryName || !galleryUrl) {
        res.status(400).json({
          error: { code: 'invalid-argument', message: 'Missing galleryName or galleryUrl' }
        });
        return;
      }

      if (!Array.isArray(recipients) || recipients.length === 0) {
        res.status(400).json({
          error: { code: 'invalid-argument', message: 'recipients must be a non-empty array' }
        });
        return;
      }

      // INVIO EMAIL
      const { createNewPhotosEmailHTML } = await import('./gmail');

      const htmlContent = createNewPhotosEmailHTML(
        galleryName,
        uploaderName,
        newPhotosCount,
        galleryUrl
      );

      const subject = `${newPhotosCount} nuova${newPhotosCount > 1 ? 'e' : ''} foto in "${galleryName}"`;

      // Aggiungi l'email alla coda invece di inviarla direttamente
      await EmailQueue.addEmailToQueue(recipients, subject, htmlContent);

      functions.logger.info(
        `✉️ Notifica nuove foto aggiunta alla coda per ${recipients.length} destinatari per ${galleryName} da uid=${uid}`
      );

      res.status(200).json({
        result: {
          success: true,
          message: 'Notification added to queue',
          queued: recipients.length
        }
      });
    } catch (error) {
      functions.logger.error('❌ Error sendNewPhotosNotificationPublic:', error);
      res.status(500).json({
        error: { code: 'internal', message: 'Failed to add notification email to queue' }
      });
    }
  });

/**
 * Function per invio password galleria (HTTP endpoint - NO AUTH REQUIRED)
 * SICUREZZA: Recupera la password direttamente da Firestore server-side
 * VALIDAZIONE: Security question validata server-side
 * Il client NON deve mai conoscere la password
 * SECRETS: Usa Firebase secrets (REPL_IDENTITY) e config per accesso Gmail API
 */
export const sendGalleryPasswordV2 = functions
  .runWith({ secrets: ['REPL_IDENTITY'] })
  .https.onRequest(async (req, res) => {
    // CORS per domini autorizzati
    const allowedOrigins = [
      'http://localhost:5173',
      'http://localhost:3000',
      'https://gennaromazzacane.it',
      'https://www.gennaromazzacane.it'
    ];

    const origin = req.headers.origin || '';
    const isAllowedOrigin = allowedOrigins.some(allowed => allowed === origin) ||
                           origin.includes('.replit.dev') || // Tutti i domini Replit
                           origin.includes('replit.app');    // Replit deployments

    if (isAllowedOrigin) {
      res.set('Access-Control-Allow-Origin', origin);
    }
    res.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.set('Access-Control-Allow-Headers', 'Content-Type');
    res.set('Access-Control-Max-Age', '3600');

    // Handle preflight
    if (req.method === 'OPTIONS') {
      res.status(204).send('');
      return;
    }

    try {
      const data = req.body.data || req.body;
      const { galleryId, recipientEmail, galleryName, galleryCode, firstName, lastName, galleryUrl, securityAnswer } = data;

      functions.logger.info(`📧 Password request received for gallery ${galleryCode} (${galleryId})`);

      if (!galleryId || !recipientEmail || !galleryName || !galleryCode) {
        functions.logger.error('Missing required parameters');
        res.status(400).json({
          error: { code: 'invalid-argument', message: 'Missing required parameters' }
        });
        return;
      }

      // SICUREZZA: Recupera password da Firestore server-side
      const galleryDoc = await admin.firestore().collection('galleries').doc(galleryId).get();

      if (!galleryDoc.exists) {
        functions.logger.error(`Gallery not found: ${galleryId}`);
        res.status(404).json({
          error: { code: 'not-found', message: 'Gallery not found' }
        });
        return;
      }

      const galleryData = galleryDoc.data();
      const galleryPassword = galleryData?.password;

      if (!galleryPassword) {
        functions.logger.error(`Gallery password not found: ${galleryId}`);
        res.status(500).json({
          error: { code: 'internal', message: 'Gallery password not configured' }
        });
        return;
      }

      // VALIDAZIONE SERVER-SIDE: Security question (se configurata)
      const hasSecurityQuestion = galleryData.requiresSecurityQuestion === true &&
                                 galleryData.securityQuestionType &&
                                 galleryData.securityAnswer;

      if (hasSecurityQuestion) {
        if (!securityAnswer) {
          functions.logger.warn(`Security answer required but not provided for gallery ${galleryId}`);
          res.status(400).json({
            error: { code: 'invalid-argument', message: 'Security answer required' }
          });
          return;
        }

        const correctAnswer = galleryData.securityAnswer.toLowerCase().trim();
        const providedAnswer = securityAnswer.toLowerCase().trim();

        if (providedAnswer !== correctAnswer) {
          functions.logger.warn(`Incorrect security answer for gallery ${galleryId}`);
          res.status(403).json({
            error: { code: 'permission-denied', message: 'Incorrect security answer' }
          });
          return;
        }

        functions.logger.info(`Security question validated successfully for gallery ${galleryId}`);
      }

      // Lazy import di gmail
      const { createGalleryPasswordEmailHTML } = await import('./gmail');

      // Crea HTML email
      const htmlContent = createGalleryPasswordEmailHTML(
        galleryName,
        galleryCode,
        galleryPassword,
        firstName,
        lastName,
        galleryUrl
      );
      const subject = `Accesso autorizzato alla galleria "${galleryName}"`;

      // Invia email tramite Gmail API
      // await sendGmailEmail(recipientEmail, subject, htmlContent); // Sostituito con l'aggiunta alla coda
      await EmailQueue.addEmailToQueue([recipientEmail], subject, htmlContent);
      functions.logger.info(`✅ Gallery password added to queue for ${recipientEmail} for gallery ${galleryName}`);

      res.status(200).json({
        result: { success: true, message: 'Gallery password added to queue', recipientEmail }
      });
    } catch (error) {
      functions.logger.error('❌ Error sending gallery password:', error);
      res.status(500).json({
        error: { code: 'internal', message: 'Failed to add gallery password email to queue' }
      });
    }
  });

/**
 * Cloud Function per invio email "Prenotazione Ricevuta"
 * Inviata automaticamente dopo che il cliente crea una booking
 */
export const sendBookingReceivedEmail = functions
  .runWith({ secrets: ['REPL_IDENTITY'] })
  .https.onRequest(async (req, res) => {
    // CORS
    const allowedOrigins = [
      'http://localhost:5173',
      'http://localhost:3000',
      'https://gennaromazzacane.it',
      'https://www.gennaromazzacane.it'
    ];

    const origin = req.headers.origin || '';
    const isAllowedOrigin = allowedOrigins.some(allowed => allowed === origin) ||
                           origin.includes('.replit.dev') ||
                           origin.includes('replit.app');

    if (isAllowedOrigin) {
      res.set('Access-Control-Allow-Origin', origin);
    }
    res.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.set('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    res.set('Access-Control-Max-Age', '3600');

    // Handle preflight
    if (req.method === 'OPTIONS') {
      res.status(204).send('');
      return;
    }

    if (req.method !== 'POST') {
      res.status(405).json({
        error: { code: 'method-not-allowed', message: 'Only POST allowed' }
      });
      return;
    }

    try {
      // AUTENTICAZIONE Firebase (opzionale per booking - guest users)
      const authHeader = req.headers.authorization || '';
      if (authHeader && authHeader.startsWith('Bearer ')) {
        const idToken = authHeader.replace('Bearer ', '').trim();
        try {
          const decoded = await admin.auth().verifyIdToken(idToken);
          functions.logger.info(`🔐 sendBookingReceivedEmail called by uid=${decoded.uid}`);
        } catch (authError) {
          // Log ma non bloccare (guest booking)
          functions.logger.warn('Auth token provided but invalid:', authError);
        }
      }

      // LETTURA DATI DAL BODY
      const data = req.body.data || req.body;
      const {
        recipientEmail,
        clienteNome,
        clienteCognome,
        campaignNome,
        dataShootingInizio,
        dataShootingFine,
        prodottoNome,
        note
      } = data || {};

      // VALIDAZIONI
      if (!recipientEmail || !clienteNome || !clienteCognome || !campaignNome || !dataShootingInizio || !dataShootingFine) {
        res.status(400).json({
          error: { code: 'invalid-argument', message: 'Missing required booking details' }
        });
        return;
      }

      // INVIO EMAIL
      const { createBookingReceivedEmailHTML } = await import('./gmail');

      const htmlContent = createBookingReceivedEmailHTML({
        clienteNome,
        clienteCognome,
        campaignNome,
        dataShootingInizio,
        dataShootingFine,
        prodottoNome,
        note: note || ''
      });

      const subject = `Prenotazione Ricevuta - ${campaignNome}`;

      // Invia email tramite Gmail API
      // await sendGmailEmail(recipientEmail, subject, htmlContent); // Sostituito con l'aggiunta alla coda
      await EmailQueue.addEmailToQueue([recipientEmail], subject, htmlContent);

      functions.logger.info(
        `✉️ Email "Prenotazione Ricevuta" added to queue for ${recipientEmail} for campaign ${campaignNome}`
      );

      res.status(200).json({
        result: {
          success: true,
          message: 'Booking received email added to queue',
          queued: 1
        }
      });
    } catch (error) {
      functions.logger.error('❌ Error sendBookingReceivedEmail:', error);
      res.status(500).json({
        error: { code: 'internal', message: 'Failed to add booking received email to queue' }
      });
    }
  });

/**
 * Cloud Function per invio email "Prenotazione Confermata"
 * Inviata dopo che l'admin approva la booking
 */
export const sendBookingConfirmedEmail = functions
  .runWith({ secrets: ['REPL_IDENTITY'] })
  .https.onRequest(async (req, res) => {
    // CORS
    const allowedOrigins = [
      'http://localhost:5173',
      'http://localhost:3000',
      'https://gennaromazzacane.it',
      'https://www.gennaromazzacane.it'
    ];

    const origin = req.headers.origin || '';
    const isAllowedOrigin = allowedOrigins.some(allowed => allowed === origin) ||
                           origin.includes('.replit.dev') ||
                           origin.includes('replit.app');

    if (isAllowedOrigin) {
      res.set('Access-Control-Allow-Origin', origin);
    }
    res.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.set('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    res.set('Access-Control-Max-Age', '3600');

    // Handle preflight
    if (req.method === 'OPTIONS') {
      res.status(204).send('');
      return;
    }

    if (req.method !== 'POST') {
      res.status(405).json({
        error: { code: 'method-not-allowed', message: 'Only POST allowed' }
      });
      return;
    }

    try {
      // AUTENTICAZIONE Firebase (opzionale - chiamata server-side da Express)
      const authHeader = req.headers.authorization || '';
      let uid = 'server';
      if (authHeader && authHeader.startsWith('Bearer ')) {
        const idToken = authHeader.replace('Bearer ', '').trim();
        try {
          const decoded = await admin.auth().verifyIdToken(idToken);
          uid = decoded.uid;
          functions.logger.info(`🔐 sendBookingConfirmedEmail called by uid=${uid}`);
        } catch (authError) {
          // Log ma non bloccare (chiamata server-side)
          functions.logger.warn('Auth token provided but invalid:', authError);
        }
      }

      // LETTURA DATI DAL BODY
      const data = req.body.data || req.body;
      const {
        recipientEmail,
        clienteNome,
        clienteCognome,
        campaignNome,
        dataShootingInizio,
        dataShootingFine,
        prodottoNome,
        note
      } = data || {};

      // VALIDAZIONI
      if (!recipientEmail || !clienteNome || !clienteCognome || !campaignNome || !dataShootingInizio || !dataShootingFine) {
        res.status(400).json({
          error: { code: 'invalid-argument', message: 'Missing required booking details' }
        });
        return;
      }

      // INVIO EMAIL
      const { createBookingConfirmedEmailHTML } = await import('./gmail');

      const htmlContent = createBookingConfirmedEmailHTML({
        clienteNome,
        clienteCognome,
        campaignNome,
        dataShootingInizio,
        dataShootingFine,
        prodottoNome,
        note: note || ''
      });

      const subject = `✅ Prenotazione Confermata - ${campaignNome}`;

      // Invia email tramite Gmail API
      // await sendGmailEmail(recipientEmail, subject, htmlContent); // Sostituito con l'aggiunta alla coda
      await EmailQueue.addEmailToQueue([recipientEmail], subject, htmlContent);

      functions.logger.info(
        `✉️ Email "Prenotazione Confermata" added to queue for ${recipientEmail} for campaign ${campaignNome} from admin uid=${uid}`
      );

      res.status(200).json({
        result: {
          success: true,
          message: 'Booking confirmed email added to queue',
          queued: 1
        }
      });
    } catch (error) {
      functions.logger.error('❌ Error sendBookingConfirmedEmail:', error);
      res.status(500).json({
        error: { code: 'internal', message: 'Failed to add booking confirmed email to queue' }
      });
    }
  });

/**
 * Function per test configurazione email
 */
export const testEmailConfiguration = functions.https.onCall(async (data, context) => {
  try {
    const { testRecipient } = data;
    const recipient = testRecipient || 'gennaro.mazzacane@gmail.com';

    // Lazy import di gmail (solo quando necessario)
    const { createTestEmailHTML } = await import('./gmail');

    // Crea HTML email
    const htmlContent = createTestEmailHTML();
    const subject = 'Test Configurazione Email - Wedding Gallery';

    // Invia email tramite Gmail API
    // await sendGmailEmail(recipient, subject, htmlContent); // Sostituito con l'aggiunta alla coda
    await EmailQueue.addEmailToQueue([recipient], subject, htmlContent);
    functions.logger.info(`Test email added to queue for ${recipient} via Gmail API`);

    return { success: true, message: 'Test email added to queue' };
  } catch (error) {
    functions.logger.error('Error adding test email to queue:', error);
    throw new functions.https.HttpsError('internal', 'Failed to add test email to queue');
  }
});

/**
 * Function per email di benvenuto
 */
export const sendWelcomeEmail = functions.https.onCall(async (data, context) => {
  try {
    const { recipientEmail, galleryName } = data;

    if (!recipientEmail || !galleryName) {
      throw new functions.https.HttpsError('invalid-argument', 'Missing required parameters');
    }

    // Lazy import di gmail (solo quando necessario)
    const { createWelcomeEmailHTML } = await import('./gmail');

    // Crea HTML email
    const htmlContent = createWelcomeEmailHTML(galleryName);
    const subject = `Benvenuto! Sei iscritto alle notifiche di "${galleryName}"`;

    // Invia email tramite Gmail API
    // await sendGmailEmail(recipientEmail, subject, htmlContent); // Sostituito con l'aggiunta alla coda
    await EmailQueue.addEmailToQueue([recipientEmail], subject, htmlContent);
    functions.logger.info(`Welcome email added to queue for ${recipientEmail} via Gmail API`);

    return { success: true, message: 'Welcome email added to queue' };
  } catch (error) {
    functions.logger.error('Error adding welcome email to queue:', error);
    throw new functions.https.HttpsError('internal', 'Failed to add welcome email to queue');
  }
});

// Import altre funzioni - TEMPORANEAMENTE DISABILITATI PER DEBUG
// import { exportGalleryAccessCSV } from './csv-export';

// Export functions
// export { exportGalleryAccessCSV };

/**
 * Proxy per scaricare immagini WordPress (bypassa CORS)
 * HTTP endpoint con CORS abilitati per supporto Replit
 */
export const downloadWordPressImage = functions.https.onRequest(async (req, res) => {
  // CORS - Identico alle altre funzioni
  const allowedOrigins = [
    'http://localhost:5173',
    'http://localhost:3000',
    'https://gennaromazzacane.it',
    'https://www.gennaromazzacane.it'
  ];

  const origin = req.headers.origin || '';
  const isAllowedOrigin = allowedOrigins.some(allowed => allowed === origin) ||
                         origin.includes('.replit.dev') ||
                         origin.includes('replit.app');

  if (isAllowedOrigin) {
    res.set('Access-Control-Allow-Origin', origin);
  }
  res.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.set('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  res.set('Access-Control-Max-Age', '3600');

  // Handle preflight
  if (req.method === 'OPTIONS') {
    res.status(204).send('');
    return;
  }

  if (req.method !== 'POST') {
    res.status(405).json({
      error: { code: 'method-not-allowed', message: 'Only POST allowed' }
    });
    return;
  }

  try {
    // AUTENTICAZIONE Firebase
    const authHeader = req.headers.authorization || '';
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      res.status(401).json({
        error: { code: 'unauthenticated', message: 'Missing Authorization Bearer token' }
      });
      return;
    }

    const idToken = authHeader.replace('Bearer ', '').trim();
    try {
      const decoded = await admin.auth().verifyIdToken(idToken);
      functions.logger.info(`🔐 downloadWordPressImage called by uid=${decoded.uid}`);
    } catch (authError) {
      functions.logger.error('Auth verification failed:', authError);
      res.status(401).json({
        error: { code: 'unauthenticated', message: 'Invalid token' }
      });
      return;
    }

    // LETTURA DATI DAL BODY
    const data = req.body.data || req.body;
    const { imageUrl, postSlug } = data || {};

    // VALIDAZIONI
    if (!imageUrl || !postSlug) {
      res.status(400).json({
        error: { code: 'invalid-argument', message: 'imageUrl e postSlug richiesti' }
      });
      return;
    }

    // Converti HTTP → HTTPS se necessario
    let urlToFetch = imageUrl;
    if (imageUrl.startsWith('http://')) {
      urlToFetch = imageUrl.replace('http://', 'https://');
      functions.logger.info(`🔄 Convertito HTTP → HTTPS: ${urlToFetch}`);
    }

    // Download immagine (server-side, bypassa CORS)
    const fetch = (await import('node-fetch')).default;
    const response = await fetch(urlToFetch);

    if (!response.ok) {
      throw new Error(`HTTP ${response.status} - ${response.statusText}`);
    }

    const buffer = await response.buffer();
    const contentType = response.headers.get('content-type') || 'image/jpeg';
    functions.logger.info(`📥 Scaricato ${buffer.length} bytes da ${urlToFetch}`);

    // Upload su Firebase Storage
    const bucket = admin.storage().bucket();
    const timestamp = Date.now();
    const filename = `blog-images/${postSlug}/${timestamp}.jpg`;
    const file = bucket.file(filename);

    await file.save(buffer, {
      contentType,
      metadata: {
        metadata: {
          originalUrl: imageUrl
        }
      }
    });

    // Rendi pubblico il file
    await file.makePublic();

    // Ottieni URL pubblico
    const publicUrl = `https://storage.googleapis.com/${bucket.name}/${filename}`;
    functions.logger.info(`✅ Immagine caricata su Firebase: ${publicUrl}`);

    res.status(200).json({
      result: { success: true, url: publicUrl }
    });

  } catch (error: any) {
    functions.logger.error('❌ Errore download immagine WordPress:', error);
    res.status(500).json({
      error: { code: 'internal', message: error.message || 'Failed to download image' }
    });
  }
});

/**
 * Cloud Function SCHEDULATA: processa la coda delle email ogni minuto.
 * Legge le email in attesa da Firestore e le invia tramite Gmail API, rispettando i limiti.
 */
export const processEmailQueue = functions
  .runWith({ 
    secrets: ['REPL_IDENTITY'],
    timeoutSeconds: 540, // 9 minuti max
    memory: '512MB' // Memoria sufficiente per processing
  })
  .pubsub.schedule('*/1 * * * *') // Esegui ogni minuto
  .timeZone('UTC')
  .onRun(async (context) => {
    functions.logger.info('⏳ Starting email queue processing...');

    try {
      // Usa il metodo processQueue che ha già distributed lock
      await EmailQueue.processQueue();
      
      functions.logger.info('✅ Email queue processing finished.');
      return null;

    } catch (error: any) {
      functions.logger.error('❌ Unhandled error during email queue processing:', {
        error: error?.message || error,
        stack: error?.stack
      });
      
      // In caso di errore critico, la funzione riproverà al prossimo trigger (1 minuto)
      return null;
    }
  });


/**
 * HTTP Endpoint per statistiche Email Queue (dashboard admin)
 * GET /getEmailQueueStats
 */
export const getEmailQueueStats = functions.https.onRequest(async (req, res) => {
  // CORS
  const allowedOrigins = [
    'http://localhost:5173',
    'http://localhost:3000',
    'https://gennaromazzacane.it',
    'https://www.gennaromazzacane.it'
  ];

  const origin = req.headers.origin || '';
  const isAllowedOrigin = allowedOrigins.some(allowed => allowed === origin) ||
                         origin.includes('.replit.dev') ||
                         origin.includes('replit.app');

  if (isAllowedOrigin) {
    res.set('Access-Control-Allow-Origin', origin);
  }
  res.set('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.set('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.status(204).send('');
    return;
  }

  if (req.method !== 'GET') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const stats = await EmailQueue.getStats();
    
    res.status(200).json({
      success: true,
      stats,
      timestamp: new Date().toISOString()
    });
  } catch (error: any) {
    functions.logger.error('❌ Error getEmailQueueStats:', error);
    res.status(500).json({
      success: false,
      error: error?.message || 'Failed to get queue stats'
    });
  }
});
