// Regressione touch: non sostituire tap con click, né usare force/dispatchEvent per i pulsanti.
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { chromium, webkit } from '@playwright/test';
import { strict as assert } from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
const root=process.cwd();
const vite=await createServer({configFile:false,root:path.join(root,'e2e/mockup-harness'),publicDir:path.join(root,'client/public'),plugins:[{name:'firebase-test',enforce:'pre',resolveId(source,importer){if(source==='@/lib/firebase'||source.replaceAll('\\','/').endsWith('/client/src/lib/firebase')||(source==='./firebase'&&importer?.replaceAll('\\','/').includes('/client/src/lib/')))return path.join(root,'e2e/mockup-harness/firebase.ts');}},react()],resolve:{alias:{'@':path.join(root,'client/src'),'@shared':path.join(root,'shared')}},css:{postcss:path.join(root,'postcss.config.js')},server:{host:'127.0.0.1',port:0,fs:{allow:[root]}}});
let browser;
let releaseRenderer;
let releaseRotating;
try {
 await vite.listen(); const port=vite.httpServer.address().port;
 const {mockupConfigurationSchema}=await vite.ssrLoadModule('/@fs/'+path.join(root,'shared/mockup-types.ts').replaceAll('\\','/'));
 const {mockupWorkflowInputSchema,mockupSelectionSchema}=await vite.ssrLoadModule('/@fs/'+path.join(root,'shared/mockup-workflow.ts').replaceAll('\\','/'));
 const engine=process.env.MOCKUP_ENGINE||'chromium';
 const edge='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
 browser=await (engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{args:['--enable-unsafe-swiftshader'],...(fs.existsSync(edge)?{executablePath:edge}:{})}: {})});
 const page=await browser.newPage({viewport:{width:390,height:844},screen:{width:390,height:844},isMobile:true,hasTouch:true});
 page.setDefaultTimeout(15000);
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const catalog=JSON.parse(fs.readFileSync('client/public/mockups/custodia-v1/peppe-lab-catalog.json','utf8'));
 const materials=catalog.variants.slice(0,2).map(v=>({id:v.id,label:v.label,supplierCode:''}));
 const offer={revision:1,updatedAt:new Date().toISOString(),options:[['11111111-1111-4111-8111-111111111111','Custodia',catalog.models[0].id],['22222222-2222-4222-8222-222222222222','Plaza','album-girevole']].map(([id,name,rendererId])=>({id,name,rendererId,supplierCode:'',active:true,materialIds:materials.map(m=>m.id),materials,labId:'lab',labName:'Laboratorio test'}))};
 const photoId='33333333-3333-4333-8333-333333333333';
 const photo=await sharp({create:{width:600,height:400,channels:3,background:'#ccbbaa'}}).png().toBuffer();
 let saved=null,locked=false;
 await page.route('**/api/**',route=>{
   const url=new URL(route.request().url());
   assert.ok(!url.pathname.endsWith('/upload'),'Il mobile sceglie solo dalla galleria');
   if(url.pathname.endsWith('/gallery-photos')) return route.fulfill({json:{photos:Array.from({length:65},(_,i)=>({id:i?`gallery-${i}`:'gallery-one',name:`Foto prova ${i}`,thumbnailUrl:'/test-photo.png',url:'/test-photo.png'})),chapters:[]}});
   if(url.pathname.endsWith('/by-token/mockup-test-token')) return route.fulfill({json:{photobook:{id:'book',name:'Album test',currentVersion:1,approval:{version:1},versions:[{version:1,pageCount:0}],locked},version:1,pages:[],requests:[]}});
   if(url.pathname.endsWith('/gallery-photo')) return route.fulfill({json:{id:photoId,name:'Foto prova',source:'gallery',width:600,height:400}});
   if(url.pathname.includes('/photos/')) return route.fulfill({contentType:'image/png',body:photo});
   if(url.pathname.endsWith('/submit')) {const data=mockupWorkflowInputSchema.parse(route.request().postDataJSON());assert.equal(data.revision,saved.revision);saved={...saved,revision:saved.revision+1,status:'submitted'};return route.fulfill({json:saved});}
   if(route.request().method()==='PUT'){const data=route.request().postDataJSON();mockupConfigurationSchema.parse(data.configuration);mockupSelectionSchema.parse(data.selection);assert.equal(data.revision,saved?.revision||0);saved={version:1,status:'draft',updatedAt:new Date().toISOString(),...data,revision:(saved?.revision||0)+1};return route.fulfill({json:saved});}
   return route.fulfill({json:{version:1,enabled:true,editable:!locked,saved,offer}});
 });
 await page.route('**/test-photo.png',route=>route.fulfill({contentType:'image/png',body:photo}));
 const rendererGate=new Promise(resolve=>{releaseRenderer=resolve;});
 await page.route('**/mockups/custodia-v1/viewer.js',async route=>{await rendererGate;await route.continue();});
 const rotatingGate=new Promise(resolve=>{releaseRotating=resolve;});
 await page.route('**/mockups/girevole-v4/viewer.js',async route=>{await rotatingGate;await route.continue();});
 await page.goto(`http://127.0.0.1:${port}/fotolibro/mockup-test-token`);
 await page.getByTestId('overlay-rotate').waitFor();
 await page.setViewportSize({width:844,height:390});
 await page.getByTestId('overlay-rotate').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Personalizza album',exact:true}).tap();
 const chooser=page.getByTestId('mockup-model-chooser');
 await chooser.waitFor();
 assert.equal(await page.locator('iframe').count(),0,'Il primo modello non deve partire prima della scelta');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.getByTestId('mockup-rotate').count(),0,'I caroselli sono usabili anche in verticale');
 await page.setViewportSize({width:844,height:390});
 await chooser.getByRole('button',{name:'Modello successivo',exact:true}).tap();
 await chooser.getByRole('button',{name:'Scopri Plaza',exact:true}).tap();
 assert.equal(await chooser.getAttribute('data-chooser-stage'),'styles');
 assert.equal(await page.locator('iframe').count(),0,'Le varianti sono statiche e non caricano il 3D');
 await chooser.getByTestId('choose-mockup-example-plaque').tap();
 const frame=page.frameLocator('iframe');
 await page.locator('iframe').waitFor({state:'attached'});
 assert.equal(await page.locator('iframe').isVisible(),false,'Non mostrare il documento autonomo prima che il wizard sia pronto');
 await page.getByText('Preparazione del tuo configuratore…',{exact:true}).waitFor();
 releaseRotating();
 await frame.locator('#wizard-slot').waitFor({timeout:45000});
 await frame.getByRole('button',{name:'Ho capito',exact:true}).tap();
 await page.waitForFunction(()=>document.querySelector('iframe')?.contentDocument.querySelector('#coverLayout')?.value==='plaque');
 await page.setViewportSize({width:390,height:844});
 await page.getByTestId('mockup-rotate').waitFor();
 await page.setViewportSize({width:844,height:390});
 await page.getByTestId('mockup-rotate').waitFor({state:'hidden'});
 // L'album mantiene l'intera altezza disponibile: comandi dentro il canvas, azioni nel pannello.
 for (const viewport of [{width:844,height:300},{width:667,height:280},{width:844,height:390}]) {
   await page.setViewportSize(viewport); await page.waitForTimeout(250);
   const stageBox=await frame.locator('.stage').boundingBox(),iframeBox=await page.locator('iframe').boundingBox();
   const modalBox=await page.locator('[data-mobile-mockup=true]').boundingBox();
   assert.ok(Math.abs(modalBox.height-viewport.height)<2,'Il modale usa tutto il viewport visibile');
   assert.ok(stageBox.height>=iframeBox.height-2,`Canvas usa altezza disponibile: ${JSON.stringify(stageBox)}`);
   assert.ok(stageBox.width>=viewport.width*.54 && stageBox.width<=viewport.width*.62,'Anteprima bilanciata con pannello opzioni più largo');
   for(const button of [frame.getByRole('button',{name:'Avanti',exact:true}),frame.getByRole('button',{name:'Torna alla scelta modello',exact:true}),frame.getByRole('button',{name:'Fronte',exact:true})]) {
     const box=await button.boundingBox(); assert.ok(box.height>=44 && box.y>=0 && box.y+box.height<=viewport.height+1,'Controlli raggiungibili senza scroll pagina');
   }
   assert.equal(await page.locator('.mockup-actions').count(),0,'Nessun footer ingombrante sul mobile');
 }
 assert.equal(await frame.locator('details.category[open],details.material-category[open]').count(),0);
 await frame.locator('.category summary,.material-category summary').first().tap();
 assert.equal(await frame.locator('details.category[open],details.material-category[open]').count(),1);
 await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 await frame.getByRole('button',{name:'Bianco',exact:true}).tap();
 assert.equal(await frame.locator('#frameFinish').inputValue(),'white');
 await frame.getByRole('button',{name:'Avvia o ferma rotazione scrigno',exact:true}).tap();
 assert.equal(await frame.locator('#rotate').getAttribute('aria-pressed'),'true');
 await frame.getByRole('button',{name:'Estrai o reinserisci album',exact:true}).tap();
 assert.equal(await frame.locator('body').getAttribute('data-extraction'),'100');
 assert.equal(await frame.locator('#rotate').getAttribute('aria-pressed'),'false');
 await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 await frame.locator('#firstName').tap();await frame.locator('#firstName').fill('Anna');
 await frame.getByRole('button',{name:'Indietro',exact:true}).tap();
 await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 assert.equal(await frame.locator('#firstName').inputValue(),'Anna');
 const normalWidth=(await frame.locator('.stage').boundingBox()).width;
 assert.ok((await frame.locator('aside').boundingBox()).width>=300,'Più larghezza per opzioni sul telefono orizzontale');
 await page.getByRole('button',{name:'Espandi anteprima',exact:true}).tap();
 assert.equal(await frame.locator('aside').isVisible(),false);
 assert.ok((await frame.locator('.stage').boundingBox()).width>normalWidth+200);
 await page.getByRole('button',{name:'Torna alle opzioni',exact:true}).tap();
 assert.equal(await frame.locator('#firstName').inputValue(),'Anna');
 assert.equal(await page.locator('input[type=file]').count(),0);
 assert.equal(await frame.getByLabel('Foto da personalizzare',{exact:true}).count(),0);
 const stageBox=await frame.locator('.stage').boundingBox(),controlsBox=await frame.locator('.wizard-iconbar').boundingBox();
 assert.ok(controlsBox.height<=44 && controlsBox.y+controlsBox.height<=stageBox.y+stageBox.height,'Icone compatte nel canvas');
 // In casa disponibile prima del riepilogo, non altera configurazione o passaggio.
 await page.getByRole('button',{name:'In casa',exact:true}).tap();
 assert.equal(await frame.locator('#homeScene').inputValue(),'sideboard');
 await frame.locator('#homeScene').selectOption('living');
 assert.equal(await frame.locator('#homeFinish option').count(),13);
 await frame.locator('#homeLighting').selectOption('evening');
 await frame.locator('.home-measures summary').tap();
 await frame.locator('#home-width').fill('180');
 await frame.locator('#home-width').press('Tab');
 assert.equal(await frame.locator('#home-width').inputValue(),'180');
 await frame.locator('#homeAlbumX').fill('60');await frame.locator('#homeAlbumX').dispatchEvent('input');
 assert.equal(await frame.locator('body').getAttribute('data-home-album-position'),'60,0');
 await page.getByRole('button',{name:'Solo album',exact:true}).tap();
 assert.equal(await frame.locator('body').getAttribute('data-wizard-step'),'4');
 assert.equal(await frame.locator('#firstName').inputValue(),'Anna');
 await page.getByRole('button',{name:'In casa',exact:true}).tap();
 assert.equal(await frame.locator('#homeScene').inputValue(),'living');
 assert.equal(await frame.locator('#homeLighting').inputValue(),'evening');
 assert.equal(await frame.locator('#home-width').inputValue(),'180');
 await frame.getByRole('button',{name:'Torna a personalizzare',exact:true}).tap();
 await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 await frame.getByRole('button',{name:'Foto a tutta superficie su plexiglass',exact:true}).tap();
 await frame.getByText('Manca la foto sul plexiglass.',{exact:false}).waitFor();
 assert.equal(await frame.getByRole('button',{name:'Avanti',exact:true}).isDisabled(),true);
 await frame.getByRole('button',{name:'Scegli dalla galleria',exact:true}).tap();
 const picker=page.getByRole('dialog',{name:'Scegli la foto del retro',exact:true});
 await picker.waitFor();
 for(const viewport of [{width:667,height:375},{width:390,height:844},{width:844,height:390}]){
   await page.setViewportSize(viewport);await page.waitForTimeout(250);
   const bounds=await picker.boundingBox();
   assert.ok(bounds && bounds.x>=-1 && bounds.y>=-1 && bounds.x+bounds.width<=viewport.width+1 && bounds.y+bounds.height<=viewport.height+1);
   await page.getByTestId('button-picker-next').tap();
   await page.getByTestId('button-pick-photo-gallery-64').waitFor();
   await page.getByTestId('button-picker-prev').tap();
 }
 await page.getByTestId('input-photo-search').fill('Foto');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.getByTestId('mockup-rotate').count(),0);
 assert.equal(await page.getByTestId('overlay-rotate').count(),0);
 await page.getByTestId('button-pick-photo-gallery-one').tap();
 await page.getByTestId('mockup-rotate').waitFor();
 await page.setViewportSize({width:844,height:390});
 await page.getByTestId('mockup-rotate').waitFor({state:'hidden'});
 await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 await frame.getByRole('button',{name:'Indietro',exact:true}).tap();
 assert.equal(await frame.locator('body').getAttribute('data-wizard-step'),'5','Si torna indietro dal riepilogo');
 await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 await frame.getByRole('button',{name:'Salva bozza',exact:true}).tap();
 await frame.getByText('Mockup salvato.',{exact:false}).waitFor();
 assert.equal(saved.configuration.backPhotoAssetId,photoId);
 assert.equal(saved.configuration.assetRevision,4);
 assert.equal(saved.configuration.engravingNames.first,'Anna');
 await frame.getByRole('button',{name:'Invia allo studio',exact:true}).tap();
 await frame.getByText('Proposta inviata allo studio per la verifica.',{exact:true}).waitFor();
 assert.equal(saved.status,'submitted');
 await page.getByRole('button',{name:'Chiudi mockup',exact:true}).tap();
 await page.getByRole('button',{name:'Apri il tuo album',exact:true}).tap();
 assert.equal(await chooser.count(),0,'La riapertura riparte dalla configurazione salvata');
 await frame.locator('#wizard-slot').waitFor({timeout:45000});
 assert.equal(await frame.locator('.wizard-gesture-guide').count(),0,'La guida iniziale non si ripete nella sessione');
 await page.getByRole('button',{name:'In casa',exact:true}).tap();
 await page.getByRole('button',{name:'Solo album',exact:true}).tap();
 assert.equal(await frame.getByText('Modifiche da salvare',{exact:true}).count(),0,'La sola esplorazione non crea revisioni');
 await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 await frame.getByRole('button',{name:'Legno naturale',exact:true}).tap();
 for(let i=0;i<3;i++) await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 await frame.getByRole('button',{name:'Salva bozza',exact:true}).tap();
 await frame.getByText('Mockup salvato.',{exact:false}).waitFor();
 assert.equal(saved.revision,3,'Nuova revisione dopo precedente invio, che ha creato la revisione 2');
 await page.screenshot({path:`work/mockup-touch-${engine}-plaza.png`});
 // Il cambio modello ritorna ai due caroselli, con renderer esistente nascosto fino alla scelta.
 await page.getByRole('button',{name:'Cambia',exact:true}).tap();
 await chooser.getByRole('button',{name:'Modello precedente',exact:true}).tap();
 await chooser.getByRole('button',{name:'Scopri Custodia',exact:true}).tap();
 assert.equal(await chooser.getByTestId('choose-mockup-example-plaque').count(),0,'Nessuna incisione non supportata su Custodia');
 await chooser.getByRole('button',{name:'Esempio successivo',exact:true}).tap();
 await chooser.getByTestId('choose-mockup-example-full').tap();
 assert.equal(await page.locator('iframe').isVisible(),false,'Nascondere il renderer durante il cambio');
 releaseRenderer();
 await frame.locator('#wizard-slot').waitFor({timeout:45000});
 await frame.getByRole('button',{name:'Avanti',exact:true}).tap();
 assert.equal(await frame.locator('body').getAttribute('data-wizard-step'),'4','Custodia non mostra un passaggio struttura vuoto');
 await page.waitForFunction(()=>document.querySelector('iframe')?.contentDocument.querySelector('#coverOptions select')?.value==='full');
 assert.equal(await frame.locator('#coverUpload').isVisible(),false,'Il selettore di file nativo non riappare in Custodia');
 assert.equal(await frame.locator('label[for=coverUpload]').isVisible(),false);
 await page.screenshot({path:`work/mockup-touch-${engine}.png`});
 page.once('dialog',dialog=>dialog.dismiss());
 await page.getByRole('button',{name:'Chiudi mockup',exact:true}).tap();
 assert.equal(await page.locator('iframe').count(),1,'Annullare la chiusura conserva il lavoro locale');
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Chiudi mockup',exact:true}).tap();
 await page.waitForFunction(()=>!document.querySelector('iframe'));
 locked=true;saved=null;
 await page.reload();
 await page.getByText('Nessun mockup salvato da consultare',{exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Personalizza album',exact:true}).count(),0,'In stampa senza mockup non propone una nuova bozza');
 assert.equal(await page.locator('iframe').count(),0);
 assert.deepEqual(errors,[]);console.log(`Touch ${engine} OK: caroselli, nessun flash studio, layout ridotto, galleria ruotata, In casa, salvataggi e riapertura.`);
} finally {releaseRenderer?.();releaseRotating?.();await browser?.close();await vite.close();}
