// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-mobile-navigation/Compact.tsx": () => import("../components/mockups/admin-mobile-navigation/Compact.tsx"),
  "./components/mockups/admin-mobile-navigation/Current.tsx": () => import("../components/mockups/admin-mobile-navigation/Current.tsx"),
  "./components/mockups/aversa-image-vision/Current.tsx": () => import("../components/mockups/aversa-image-vision/Current.tsx"),
  "./components/mockups/aversa-image-vision/Proposal.tsx": () => import("../components/mockups/aversa-image-vision/Proposal.tsx"),
  "./components/mockups/image-vision-style/BlueRefined.tsx": () => import("../components/mockups/image-vision-style/BlueRefined.tsx"),
  "./components/mockups/image-vision-style/Current.tsx": () => import("../components/mockups/image-vision-style/Current.tsx")
};
