// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/photobook-chooser/Comparison.tsx": () => import("../components/mockups/photobook-chooser/Comparison.tsx"),
  "./components/mockups/photobook-chooser/Current.tsx": () => import("../components/mockups/photobook-chooser/Current.tsx"),
  "./components/mockups/photobook-chooser/Editorial.tsx": () => import("../components/mockups/photobook-chooser/Editorial.tsx"),
  "./components/mockups/photobook-chooser/MobileFirst.tsx": () => import("../components/mockups/photobook-chooser/MobileFirst.tsx"),
  "./components/mockups/photobook-configurator/AdminClarity.tsx": () => import("../components/mockups/photobook-configurator/AdminClarity.tsx"),
  "./components/mockups/photobook-configurator/Current.tsx": () => import("../components/mockups/photobook-configurator/Current.tsx")
};
