import { Link, useRoute } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import Navigation from '@/components/Navigation';
import { useSEO } from '@/hooks/useSEO';

const identity = 'Image Studio Fotografico di Gennaro Mazzacane è uno studio di fotografia matrimoniale ad Aversa, attivo principalmente tra Caserta, Napoli e Campania, specializzato in fotografia spontanea, reportage ed editoriale.';

const pages: Record<string, { title: string; description: string; heading: string; intro: string; question: string; answer: string }> = {
  '/fotografo-matrimonio-caserta': { title: 'Fotografo Matrimonio Caserta | Image Studio', description: 'Fotografo di matrimonio a Caserta: reportage spontaneo, editoriale e consulenza personalizzata con Image Studio di Gennaro Mazzacane.', heading: 'Fotografo matrimonio Caserta', intro: 'Raccontiamo matrimoni a Caserta e provincia con immagini naturali, eleganti e fedeli a ciò che accade davvero.', question: 'Cerchi un fotografo di matrimonio a Caserta?', answer: 'Image Studio segue matrimoni a Caserta con un approccio spontaneo, di reportage ed editoriale. Ogni servizio viene progettato attorno alla coppia, alla cerimonia e alla location.' },
  '/fotografo-matrimonio-napoli': { title: 'Fotografo Matrimonio Napoli | Image Studio', description: 'Fotografo di matrimonio a Napoli: fotografia spontanea, reportage ed editoriale per coppie che desiderano un racconto autentico.', heading: 'Fotografo matrimonio Napoli', intro: 'Dai preparativi alla festa, trasformiamo il matrimonio a Napoli in un racconto fotografico autentico e personale.', question: 'Cerchi un fotografo di matrimonio a Napoli?', answer: 'Image Studio lavora a Napoli e in Campania per raccontare matrimoni con discrezione, cura della luce e attenzione ai momenti irripetibili.' },
  '/fotografo-matrimonio-spontaneo': { title: 'Fotografo Matrimonio Spontaneo | Image Studio', description: 'Fotografia di matrimonio spontanea: reportage, emozioni vere e immagini editoriali firmate Image Studio.', heading: 'Fotografo matrimonio spontaneo', intro: 'La fotografia spontanea non forza i momenti: li osserva, li anticipa e li restituisce con sensibilità.', question: 'Che cosa significa fotografia di matrimonio spontanea?', answer: 'Significa lasciare spazio alle persone e alle emozioni reali. Interveniamo solo quando serve, per ottenere immagini curate senza trasformare il vostro giorno in una posa continua.' },
  '/quanto-costa-fotografo-matrimonio-caserta': { title: 'Quanto Costa un Fotografo di Matrimonio a Caserta | Image Studio', description: 'Quanto costa un fotografo di matrimonio a Caserta? Una guida chiara su servizi, variabili di prezzo e preventivo personalizzato.', heading: 'Quanto costa un fotografo di matrimonio a Caserta?', intro: 'Un preventivo utile parte dalle vostre esigenze reali, non da un listino uguale per tutti.', question: 'Quanto costa un fotografo di matrimonio a Caserta?', answer: 'Il prezzo dipende da durata, numero di operatori, video, album e servizi inclusi. Per un servizio completo professionale nella zona di Caserta la fascia può variare sensibilmente: per questo prepariamo un preventivo chiaro e personalizzato dopo aver conosciuto il vostro matrimonio.' },
};

export function WeddingCommercialPage({ path }: { path: string }) {
  const page = pages[path];
  useSEO({ title: page.title, description: page.description, canonical: path, keywords: `${page.heading}, fotografia matrimonio Campania, Gennaro Mazzacane, Image Studio` });
  return <div className="min-h-screen bg-white"><Navigation /><main className="pt-28">
    <section className="bg-[#2C3A2C] px-5 py-20 text-center text-white"><div className="mx-auto max-w-3xl"><p className="mb-4 text-sm uppercase tracking-[.18em] text-[#d9a486]">Image Studio Fotografico</p><h1 className="font-playfair text-4xl md:text-6xl">{page.heading}</h1><p className="mx-auto mt-6 max-w-2xl text-lg text-white/80">{page.intro}</p></div></section>
    <section className="mx-auto max-w-4xl px-5 py-16"><p className="text-lg leading-8 text-slate-700">{identity}</p><div className="my-12 rounded-2xl border border-[#c4724a]/30 bg-[#F5EFE6] p-8"><h2 className="font-playfair text-3xl text-[#2C3A2C]">{page.question}</h2><p className="mt-4 leading-7 text-slate-700">{page.answer}</p></div><h2 className="font-playfair text-3xl text-[#2C3A2C]">Un racconto costruito attorno a voi</h2><p className="mt-4 leading-7 text-slate-700">Dalla consulenza alla consegna, definiamo insieme il ritmo della giornata, le priorità e i servizi utili. Il risultato è un archivio di immagini che conserva persone, relazioni e atmosfera.</p><nav className="mt-10 flex flex-wrap gap-x-5 gap-y-3 text-sm font-medium text-[#c4724a]"><Link href="/fotografo-matrimonio-caserta">Fotografo matrimonio Caserta</Link><Link href="/fotografo-matrimonio-napoli">Fotografo matrimonio Napoli</Link><Link href="/fotografo-matrimonio-spontaneo">Fotografo matrimonio spontaneo</Link><Link href="/quanto-costa-fotografo-matrimonio-caserta">Prezzi fotografo matrimonio Caserta</Link></nav><div className="mt-8 flex flex-wrap gap-4"><Link href="/portfolio/matrimonio" className="rounded-full bg-[#c4724a] px-6 py-3 font-medium text-white">Guarda i matrimoni reali</Link><Link href="/consulenze" className="rounded-full border border-[#2C3A2C] px-6 py-3 font-medium text-[#2C3A2C]">Richiedi una consulenza</Link></div></section>
  </main></div>;
}

export default function WeddingStoryPage() {
  const [, params] = useRoute('/matrimoni/:slug'); const slug = params?.slug || '';
  const { data: story, isLoading } = useQuery({ queryKey: ['wedding-seo', slug], queryFn: async () => { const res = await fetch(`/api/public/matrimoni/${slug}`); if (!res.ok) throw new Error(); return res.json(); } });
  useSEO({ title: story?.title || 'Matrimonio reale | Image Studio', description: story?.description || identity, canonical: `/matrimoni/${slug}`, ogType: 'article', ogImage: story?.coverImage });
  if (isLoading) return <div className="min-h-screen bg-white" />;
  if (!story) return <div className="min-h-screen bg-white"><Navigation /><main className="pt-32 text-center"><h1 className="font-playfair text-4xl">Storia non disponibile</h1></main></div>;
  return <div className="min-h-screen bg-white"><Navigation /><main className="pt-28"><article className="mx-auto max-w-4xl px-5 py-12"><p className="text-sm uppercase tracking-widest text-[#c4724a]">Matrimonio reale in {story.municipality}</p><h1 className="mt-3 font-playfair text-4xl text-[#2C3A2C] md:text-6xl">{story.title}</h1>{story.coverImage && <img src={story.coverImage} alt={story.title} className="mt-8 max-h-[600px] w-full rounded-2xl object-cover" />}<dl className="my-10 grid gap-5 rounded-2xl bg-[#F5EFE6] p-7 sm:grid-cols-2"><div><dt className="font-semibold">Sposi</dt><dd>{story.names}</dd></div><div><dt className="font-semibold">Location</dt><dd>{story.location}, {story.municipality}</dd></div>{story.church && <div><dt className="font-semibold">Cerimonia</dt><dd>{story.church}</dd></div>}<div><dt className="font-semibold">Stile</dt><dd>{story.style}</dd></div></dl><p className="whitespace-pre-line text-lg leading-8 text-slate-700">{story.story}</p>{story.images?.length > 0 && <div className="mt-12 space-y-10">{['Preparativi', 'Cerimonia', 'Coppia', 'Location e ricevimento', 'Festa'].map((section: string) => { const pictures = story.images.filter((image: any) => image.section === section); return pictures.length ? <section key={section}><h2 className="mb-4 font-playfair text-3xl text-[#2C3A2C]">{section}</h2><div className="grid gap-4 sm:grid-cols-2">{pictures.map((image: any) => <img key={image.url} src={image.url} alt={image.alt} loading="lazy" className="w-full rounded-xl object-cover" />)}</div></section> : null; })}</div>}<h2 className="mt-14 font-playfair text-3xl text-[#2C3A2C]">Domande frequenti</h2><div className="mt-6 space-y-4">{story.faq.map((faq: any) => <section key={faq.question} className="rounded-xl border p-5"><h3 className="font-semibold text-[#2C3A2C]">{faq.question}</h3><p className="mt-2 text-slate-700">{faq.answer}</p></section>)}</div><nav className="mt-12 flex flex-wrap gap-4 text-[#c4724a]"><Link href="/fotografo-matrimonio-caserta">Fotografo matrimonio Caserta</Link><Link href="/fotografo-matrimonio-napoli">Fotografo matrimonio Napoli</Link><Link href="/fotografo-aversa">Fotografo Aversa</Link></nav></article></main></div>;
}
